=== anirudhsundar/autodl/src/autodl/repo_names.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "array",
    "title": "Simple to to download and manage latest releases from github",
    "description": "A simple tool that reads repository information from repo_names.json in the current directory and downloads the latest release versions or any specified version of the given repos from github. It also supports extracting the downloaded file, and setting up the PATH variable to point to the bin directory",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "description": "Name of the final binary. Eg: `gh` for the github cli downloaded from the releases of [https://github.com/cli/cli](https://github.com/cli/cli)",
                "type": "string"
            },
            "user": {
                "description": "The user/organization part of github url. Eg: `sharkdp` in the URL [https://github.com/sharkdp/bat](https://github.com/sharkdp/bat)",
                "type": "string"
            },
            "repo": {
                "description": "The repository part of github url. Eg: `bat` in the URL [https://github.com/sharkdp/bat](https://github.com/sharkdp/bat)",
                "type": "string"
            },
            "file_pattern": {
                "description": "The filename to be downloaded with ### replacing the version. Eg: `gh_2.13.0_linux_amd64.tar.gz` becomes `gh_###_linux_amd64.tar.gz`",
                "type": "string"
            },
            "bin_dir_pattern": {
                "description": "The directory path to bin, created after uncompressing. Eg: `broot_all/build/x86_64-unknown-linux-musl` if path to bin directory from extracted root directory is `broot_all/build/x86_64-unknown-linux-musl/bin`",
                "type": "string"
            },
            "uncompress_cmd": {
                "description": "Command to use if the downloaded file has to be uncompressed automatically. Eg: `tar` or `unzip`",
                "type": "string"
            },
            "uncompress": {
                "description": "Whether to uncompress the downloaded file. The `uncompress_cmd` and `uncompress_flags` keys are not used if this is false",
                "type": "boolean"
            },
            "uncompress_flags": {
                "description": "Flags/options to pass to the uncompress_cmd if it is used. Eg: `zxf` for tar command to extract a `.tar.gz` file",
                "type": "string"
            },
            "tag_replace": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "description": "Sometimes the tag part of the URL contains some extra characters added like v1.4.0 for version 1.4.0. Here the character 'v' would only be present in the tag and not in the filename, and hence has to be removed from the file name when generating the URL for download ",
                "minItems": 2,
                "maxItems": 2
            },
            "copy_to_bin": {
                "description": "If there is just a single binary, it could be copied directly to ~/.bin which would already be in the PATH. This can be used for smaller tools that only contain a single binary and no dependencies",
                "type": "boolean"
            },
            "releases": {
                "description": "By default this is set to latest, and if we would like to use a different tag, that tag can be menstioned here",
                "default": "latest",
                "type": "string"
            },
            "copy_source_name": {
                "description": "If the original source filename is different from what we would like to use for the command, mention the source filename here",
                "type": "string"
            },
            "chmod": {
                "description": "If you would like to update permissions for the copied binary, pass the chmod flags here",
                "type": "string"
            }
        },
        "required": [
            "bin_dir_pattern",
            "file_pattern",
            "name",
            "repo",
            "uncompress",
            "user"
        ]
    }
}

=== anirudhsundar/autodl/src/autodl/repo_names.json
[
    {
        "name": "clangd",
        "user": "clangd",
        "repo": "clangd",
        "file_pattern": "clangd-linux-###.zip",
        "bin_dir_pattern": "clangd_###/bin",
        "uncompress_cmd": "unzip",
        "uncompress": true
    },
    {
        "name": "code-minimap",
        "user": "wfxr",
        "repo": "code-minimap",
        "file_pattern": "code-minimap-###-x86_64-unknown-linux-gnu.tar.gz",
        "bin_dir_pattern": "code-minimap-###-x86_64-unknown-linux-gnu",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true
    },
    {
        "name": "gh",
        "user": "cli",
        "repo": "cli",
        "file_pattern": "gh_###_linux_amd64.tar.gz",
        "tag_replace": ["v",""],
        "bin_dir_pattern": "gh_###_linux_amd64/bin",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true
    },
    {
        "name": "clang",
        "user": "llvm",
        "repo": "llvm-project",
        "file_pattern": "clang+llvm-###-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        "tag_replace": ["llvmorg-",""],
        "bin_dir_pattern": "clang+llvm-###-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "xf",
        "releases": "llvmorg-14.0.0",
        "uncompress": true
    },
    {
        "name": "rg",
        "user": "BurntSushi",
        "repo": "ripgrep",
        "file_pattern": "ripgrep-###-x86_64-unknown-linux-musl.tar.gz",
        "bin_dir_pattern": "ripgrep-###-x86_64-unknown-linux-musl",
        "copy_to_bin": true,
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true
    },
    {
        "name": "difft",
        "user": "Wilfred",
        "repo": "difftastic",
        "file_pattern": "difft-x86_64-unknown-linux-gnu.tar.gz",
        "bin_dir_pattern": "",
        "copy_to_bin": true,
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true
    },
    {
        "name": "zoxide",
        "user": "ajeetdsouza",
        "repo": "zoxide",
        "file_pattern": "zoxide-###-x86_64-unknown-linux-musl.tar.gz",
        "bin_dir_pattern": "",
        "copy_to_bin": true,
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "tag_replace": ["v",""],
        "uncompress": true
    },
    {
        "name": "bat",
        "user": "sharkdp",
        "repo": "bat",
        "file_pattern": "bat-###-x86_64-unknown-linux-musl.tar.gz",
        "bin_dir_pattern": "bat-###-x86_64-unknown-linux-musl",
        "copy_to_bin": true,
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true
    },
    {
        "name": "lf",
        "user": "gokcehan",
        "repo": "lf",
        "file_pattern": "lf-linux-amd64.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "",
        "copy_to_bin": true
    },
    {
        "name": "glow",
        "user": "charmbracelet",
        "repo": "glow",
        "file_pattern": "glow_1.4.1_linux_x86_64.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "",
        "copy_to_bin": true,
        "tag_replace": ["v",""]
    },
    {
        "name": "broot",
        "user": "Canop",
        "repo": "broot",
        "tag_replace": ["v",""],
        "file_pattern": "broot_###.zip",
        "uncompress_cmd": "unzip",
        "uncompress_flags": "-dbroot_all",
        "uncompress": true,
        "bin_dir_pattern": "broot_all/build/x86_64-unknown-linux-musl"
    },
    {
        "name": "pandoc",
        "user": "jgm",
        "repo": "pandoc",
        "file_pattern": "pandoc-###-linux-amd64.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "pandoc-###-linux-amd64/bin"
    },
    {
        "name": "nvim",
        "user": "neovim",
        "repo": "neovim",
        "file_pattern": "nvim-linux64.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "nvim-linux64/bin",
        "releases": "v0.7.0"
    },
    {
        "name": "jq",
        "user": "stedolan",
        "repo": "jq",
        "file_pattern": "jq-linux64",
        "uncompress": false,
        "bin_dir_pattern": "",
        "copy_to_bin": true,
        "copy_source_name": "jq-linux64",
        "chmod": "+x"
    },
    {
        "name": "git-lfs",
        "user": "git-lfs",
        "repo": "git-lfs",
        "file_pattern": "git-lfs-linux-amd64-###.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "",
        "copy_to_bin": true
    },
    {
        "name": "starship",
        "user": "starship",
        "repo": "starship",
        "file_pattern": "starship-x86_64-unknown-linux-musl.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "",
        "copy_to_bin": true
    },
    {
        "name": "fd",
        "user": "sharkdp",
        "repo": "fd",
        "file_pattern": "fd-###-x86_64-unknown-linux-musl.tar.gz",
        "uncompress_cmd": "tar",
        "uncompress_flags": "zxf",
        "uncompress": true,
        "bin_dir_pattern": "fd-###-x86_64-unknown-linux-musl",
        "copy_to_bin": true
    },
    {
        "name": "exa",
        "user": "ogham",
        "repo": "exa",
        "file_pattern": "exa-linux-x86_64-###.zip",
        "uncompress_cmd": "unzip",
        "uncompress_flags": "-dexa",
        "uncompress": true,
        "bin_dir_pattern": "exa/bin",
        "copy_to_bin": true
    }
]
